#
name: Create and publish Docker image

on:
  push:
    branches: ["release"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pop-booking

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            /tmp/.buildx-cache
            ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=true
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-HHmmss' tz='UTC'}}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            type=local,src=${{ steps.composer-cache.outputs.dir }}
          cache-to: |
            type=local,dest=/tmp/.buildx-cache
            type=local,dest=${{ steps.composer-cache.outputs.dir }}

  # build-and-push-arm-image:
  #   runs-on: self-hosted
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - run: cargo build --release

  #     - name: Build Image
  #       id: build-image
  #       uses: redhat-actions/buildah-build@v2
  #       with:
  #         image: ${{ env.IMAGE_NAME }}
  #         tags: aarch64 ${{ github.sha }}
  #         platform: linux/arm64
  #         containerfiles: |
  #           ./Dockerfile

  #     - name: Push To ghcr Registry
  #       uses: redhat-actions/push-to-registry@v2
  #       with:
  #         image: ${{ env.IMAGE_NAME }}
  #         tags: ${{ steps.build-image.outputs.tags }}
  #         registry: ${{ env.REGISTRY }}/${{ github.repository_owner }} 
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
